export const achievements = [
  {
    id: "first_task",
    title: "Новачок у дії",
    description: "Завершіть своє перше завдання!",
    field: "completedTasksCount",
    goal: 1,
    type: "greaterOrEqual",
    icon: "CheckCircle",
  },
  {
    id: "tasks_10",
    title: "Збірник справ",
    description: "Виконайте 10 завдань.",
    field: "completedTasksCount",
    goal: 10,
    type: "greaterOrEqual",
    icon: "Trophy",
  },
  {
    id: "tasks_50",
    title: "Вже на півдорозі",
    description: "Виконайте 50 завдань.",
    field: "completedTasksCount",
    goal: 50,
    type: "greaterOrEqual",
    icon: "Star",
  },
  {
    id: "tasks_100",
    title: "Майстер завдань",
    description: "Виконайте 100 завдань.",
    field: "completedTasksCount",
    goal: 100,
    type: "greaterOrEqual",
    icon: "Crown",
  },
  {
    id: "first_streak",
    title: "Три дні вогню",
    description: "Завершуйте завдання протягом 3 днів поспіль.",
    field: "streak",
    goal: 3,
    type: "greaterOrEqual",
    icon: "Flame",
  },
  {
    id: "streak_7",
    title: "Тиждень чемпіона",
    description: "Завершуйте завдання 7 днів поспіль.",
    field: "streak",
    goal: 7,
    type: "greaterOrEqual",
    icon: "Calendar",
  },
  {
    id: "streak_30",
    title: "Безперервний герой",
    description: "30 днів без перерви — неймовірно!",
    field: "streak",
    goal: 30,
    type: "greaterOrEqual",
    icon: "Shield",
  },
  {
    id: "first_login",
    title: "Початок подорожі",
    description: "Увійдіть у свій акаунт вперше.",
    field: "loginsCount",
    goal: 1,
    type: "equal",
    icon: "LogIn",
  },
  {
    id: "early_bird",
    title: "Сонце піднялося разом зі мною",
    description: "Завершіть завдання до 8 ранку.",
    field: "earlyTasksCount",
    goal: 1,
    type: "greaterOrEqual",
    icon: "Sunrise",
  },
  {
    id: "late_completer",
    title: "Вартовий ночі",
    description: "Завершіть завдання після 23:00.",
    field: "lateTasksCount",
    goal: 1,
    type: "greaterOrEqual",
    icon: "Moon",
  },
  {
    id: "missed_deadline",
    title: "Перевірка на міцність",
    description: "Пропустіть дедлайн хоча б одного завдання.",
    field: "missedDeadlinesCount",
    goal: 1,
    type: "greaterOrEqual",
    hidden: true,
    icon: "AlertTriangle",
  },
  {
    id: "night_mode",
    title: "Темний лицар",
    description: "Активуйте темну тему.",
    field: "enabledDarkMode",
    goal: true,
    type: "equal",
    icon: "Palette",
  },
  {
    id: "edit_profile",
    title: "Особистий штрих",
    description: "Відредагуйте профіль.",
    field: "editedProfile",
    goal: true,
    type: "equal",
    icon: "User",
  },
  {
    id: "task_streak_break",
    title: "Падіння легенди",
    description: "Втратьте стрік з 7+ днів.",
    field: "streakBreaksCount",
    goal: 1,
    type: "greaterOrEqual",
    hidden: true,
    icon: "TrendingDown",
  },
];
